name: Update Existing Custom Chat Mode
description: Propose updates or improvements to an existing custom chat mode
title: "[UPDATE CUSTOM CHAT MODE] "
labels: ["enhancement", "chat-mode", "update"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for proposing updates to an existing custom chat mode! Please fill out the form below to help us understand your proposed changes.

  - type: input
    id: existing-custom-chat-mode
    attributes:
      label: Existing Custom Chat Mode
      description: Which custom chat mode do you want to update? (Include the .chatmode.md extension)
      placeholder: e.g., expert_dotnet_software_engineer.chatmode.md
    validations:
      required: true

  - type: dropdown
    id: update-type
    attributes:
      label: Type of Update
      description: What type of update are you proposing?
      options:
        - Bug fix - Correct existing functionality
        - Enhancement - Add new capabilities
        - Content update - Update instructions or guidelines
        - Tool changes - Add/remove/modify tools
        - Performance improvement - Optimize existing functionality
        - Documentation - Update descriptions or examples
        - Security - Address security concerns
        - Compatibility - Update for new versions/frameworks
    validations:
      required: true

  - type: textarea
    id: current-issue
    attributes:
      label: Current Issue or Limitation
      description: What specific problem or limitation does the current custom chat mode have?
      placeholder: Describe the current issue, limitation, or area for improvement...
    validations:
      required: true

  - type: textarea
    id: proposed-changes
    attributes:
      label: Proposed Changes
      description: Describe the specific changes you want to make
      placeholder: Detail the exact changes you propose to make...
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why are these changes needed? What benefits will they provide?
      placeholder: Explain why these changes are important and what benefits they will provide...
    validations:
      required: true

  - type: checkboxes
    id: affected-areas
    attributes:
      label: Areas Affected
      description: Which parts of the chat mode will be affected by your changes?
      options:
        - label: Chat mode description
        - label: Instructions section
        - label: Tools array
        - label: Response guidelines
        - label: Quality standards
        - label: Context information
        - label: Examples
        - label: Industry references

  - type: checkboxes
    id: tools-changes
    attributes:
      label: Tool Changes (if applicable)
      description: If you're proposing changes to tools, which ones?
      options:
        - label: Add workspace tool
        - label: Add read_file tool
        - label: Add list_dir tool
        - label: Add semantic_search tool
        - label: Add grep_search tool
        - label: Add create_file tool
        - label: Add replace_string_in_file tool
        - label: Add run_in_terminal tool
        - label: Remove existing tools
        - label: No tool changes

  - type: textarea
    id: tool-justification
    attributes:
      label: Tool Change Justification
      description: If proposing tool changes, explain why these specific tools are needed or should be removed
      placeholder: Explain the reasoning behind proposed tool changes...

  - type: textarea
    id: backward-compatibility
    attributes:
      label: Backward Compatibility
      description: Will your changes break existing usage? How can we minimize disruption?
      placeholder: Describe any compatibility concerns and mitigation strategies...

  - type: textarea
    id: testing-approach
    attributes:
      label: Testing Approach
      description: How should these changes be tested to ensure they work correctly?
      placeholder: Describe how to test the proposed changes...
    validations:
      required: true

  - type: textarea
    id: example-usage
    attributes:
      label: Example Usage
      description: Provide an example of how the updated chat mode would be used
      placeholder: |
        **Scenario:** [Describe the usage scenario]
        **User Input:** [Example user input]
        **Expected Behavior:** [How the updated chat mode should respond]
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions Considered
      description: What other approaches did you consider? Why is your proposed solution the best?
      placeholder: Describe alternative approaches and why you chose this one...

  - type: dropdown
    id: impact-level
    attributes:
      label: Impact Level
      description: How significant are these changes?
      options:
        - Low - Minor improvements with minimal risk
        - Medium - Notable improvements with some risk
        - High - Major changes with significant impact
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgently are these changes needed?
      options:
        - Critical - Fixes broken functionality
        - High - Addresses significant pain points
        - Medium - Notable improvement
        - Low - Nice to have enhancement
    validations:
      required: true

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
      description: Any specific implementation details or considerations?
      placeholder: Provide any technical details or implementation notes...

  - type: textarea
    id: documentation-updates
    attributes:
      label: Documentation Updates Required
      description: What documentation needs to be updated alongside these changes?
      placeholder: List any documentation that needs updating (README, examples, etc.)...

  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues or Discussions
      description: Link to any related issues, discussions, or pull requests
      placeholder: Provide links to related GitHub issues, discussions, or PRs...

  - type: checkboxes
    id: volunteering
    attributes:
      label: Volunteering
      description: How would you like to contribute to this update?
      options:
        - label: I am willing to implement these changes
        - label: I can provide domain expertise for review
        - label: I can help test the implementation
        - label: I can update related documentation
        - label: I can provide additional examples

  - type: checkboxes
    id: checklist
    attributes:
      label: Submission Checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have clearly identified the existing chat mode to update
          required: true
        - label: I have described the current issue or limitation
          required: true
        - label: I have provided specific, actionable proposed changes
          required: true
        - label: I have explained the rationale and benefits
          required: true
        - label: I have considered backward compatibility
          required: true
        - label: I have provided a testing approach
          required: true
        - label: I have included example usage of the updated chat mode
          required: true
